Update biuld.yml

diff --git a/.github/workflows/biuld.yml b/.github/workflows/biuld.yml
--- a/.github/workflows/biuld.yml
+++ b/.github/workflows/biuld.yml
@@ -3,6 +3,8 @@
 # edition and modified base of the Ing<wjz304>
 # This is free software, licensed under the MIT License.
 # See /LICENSE for more information.
+# "At the runs orders adjunction(tag on) symbol | 
+#  the code is run to sequence of the line"
 #
 
 name: Build OpenWrt
@@ -89,24 +91,32 @@ jobs:
           
           sudo ${GITHUB_WORKSPACE}/build.sh "${GITHUB_WORKSPACE}/${{ matrix.config }}"
 
+      - name: create the files
+        run: |
+          cd /mnt/openwrt
           ls -al
-          if [ $(ls *.img.gz | wc -l) -le 0 ]; then
-            echo "No firmware found"
-            exit 1
-          fi
-          
+            if [ $(ls *.img.gz | wc -l) -le 0 ]; then
+              echo "No firmware found"
+              exit 1
+            fi
           sudo zip -q -r $(basename "${{ matrix.config }}" .config | awk -F';' '{printf $1"-"$3}')-${{ env.release }}.zip *.img.gz
+            if [ $? -ne 0 ]; then
+              echo "Failed to condense the files"
+              exit 1
+            else
+              echo "Successfully updated the files Condense"
+            fi
 
       - name: Wait for file operations to complete
         run: 
           sleep 10 # 等待 10 秒
         
       - name: Check file permissions
-        run: 
+        run: |  
           ls -l /mnt/openwrt/*.zip
         
       - name: Wait for file operations to complete
-        run: 
+        run: |
           sleep 10 # 等待 10 秒
         
       - name: Upload firmware to release
@@ -127,7 +137,7 @@ jobs:
       - name: Remove old Releases
         uses: dev-drprasad/delete-older-releases@v0.1.0
         with:
-          keep_latest: 20
+          keep_latest: 12
           delete_tags: true
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
