Update biuld.yml

diff --git a/.github/workflows/biuld.yml b/.github/workflows/biuld.yml
--- a/.github/workflows/biuld.yml
+++ b/.github/workflows/biuld.yml
@@ -1,15 +1,17 @@
 #
-# Copyright (C) 2022 Ing <https://github.com/wjz304>
-#
+# 2025 Alon<https://github.com/xiealon>
+# edition and modified base of the Ing<wjz304>
 # This is free software, licensed under the MIT License.
 # See /LICENSE for more information.
+# "At the runs orders adjunction(tag on) symbol | 
+#  the code is run to sequence of the line"
 #
 
 name: Build OpenWrt
 
 on:
   schedule:
-    - cron: "0 0 1/2 * *"
+    - cron: "0 0 2/12 * *"
   workflow_dispatch:
 
 jobs:
@@ -47,10 +49,12 @@ jobs:
       - name: Checkout
         uses: actions/checkout@main
 
-      #- name: Free Disk Space (Ubuntu)
-      #  uses: jlumbroso/free-disk-space@main
-      #  with:
-      #    tool-cache: true
+      # don't modify to run
+      # - name: Free Disk Space (Ubuntu)
+      #   uses: jlumbroso/free-disk-space@main
+      #   with:
+      #        tool-cache: true
+          
 
       - name: Init Env
         env:
@@ -62,6 +66,11 @@ jobs:
 
           sudo apt update
           sudo apt full-upgrade -y
+          sudo apt install -y jq
+          sudo apt install -y sed
+          sudo apt install -y coreutils
+          sudo apt-get install libc6-i386 lib32z1
+          sudo apt install -y bash bc lm-sensors wsdd2 smartmontools ntpdate
           sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
           bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext \
           genisoimage git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev \
@@ -69,32 +78,53 @@ jobs:
           libreadline-dev libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf \
           python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion \
           swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
-
-          # sudo apt install --reinstall libc6
-          # sudo systemctl daemon-reload
-          sudo apt -y autoremove --purge
+          sudo apt-get -y install libz-dev python3.5 python2.7 lib32gcc1 git-core upx
+          sudo apt install --reinstall libc6
+          sudo systemctl daemon-reload
+          # sudo apt -y autoremove --purge
           sudo apt -y clean
 
-          git clone --depth=1 https://github.com/openwrt-dev/po2lmo
+          git clone --depth=1 https://github.com/xiealon/po2lmo
           (cd po2lmo && sudo make && sudo make install)
 
           df -h
-
+      
       - name: make
         run: |
           sudo mkdir -p /mnt/openwrt
 
           cd /mnt/openwrt
-          sudo "${GITHUB_WORKSPACE}/build.sh" "${GITHUB_WORKSPACE}/${{ matrix.config }}" "true"
+          
+          sudo ${GITHUB_WORKSPACE}/build.sh "${GITHUB_WORKSPACE}/${{ matrix.config }}"
 
+      - name: create the files
+        run: |
+          cd /mnt/openwrt
           ls -al
-          if [ $(ls *.img.gz | wc -l) -le 0 ]; then
-            echo "No firmware found"
-            exit 1
-          fi
-
+            if [ $(ls *.img.gz | wc -l) -le 0 ]; then
+              echo "No firmware found"
+              exit 1
+            fi
           sudo zip -q -r $(basename "${{ matrix.config }}" .config | awk -F';' '{printf $1"-"$3}')-${{ env.release }}.zip *.img.gz
+            if [ $? -ne 0 ]; then
+              echo "Failed to condense the files"
+              exit 1
+            else
+              echo "Successfully updated the files Condense"
+            fi
 
+      - name: Wait for file operations to complete
+        run: 
+          sleep 10 # 等待 10 秒
+        
+      - name: Check file permissions
+        run: |  
+          ls -l /mnt/openwrt/*.zip
+        
+      - name: Wait for file operations to complete
+        run: |
+          sleep 10 # 等待 10 秒
+        
       - name: Upload firmware to release
         uses: softprops/action-gh-release@v2
         if: success() && !cancelled()
@@ -104,16 +134,16 @@ jobs:
           tag_name: ${{ env.release }}
           files: /mnt/openwrt/*.zip
 
-    # - name: Delete workflow runs
-    #   uses: Mattraks/delete-workflow-runs@v2
-    #   with:
-    #     retain_days: 1
-    #     keep_minimum_runs: 9
+      - name: Delete workflow runs
+        uses: Mattraks/delete-workflow-runs@v2
+        with:
+         retain_days: 0
+         keep_minimum_runs: 6
 
-    # - name: Remove old Releases
-    #   uses: dev-drprasad/delete-older-releases@v0.1.0
-    #   with:
-    #     keep_latest: 9
-    #     delete_tags: true
-    #   env:
-    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Remove old Releases
+        uses: dev-drprasad/delete-older-releases@v0.1.0
+        with:
+          keep_latest: 12
+          delete_tags: true
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
